travis:
  secure:
    BINSTAR_TOKEN: F9FA1RC+SZdMMwSYEq6za9N86WzLfZYhjbQmN4OKS9MhX81M6YBcFDvfxEeiRpvpVd0NG4FtbhMAzSZFuoIQ9dOGdttFyhfCR0GpB+LVeutcjAFHaAlpKi/7UCLK7E/Zi1sqttUfvEExCgqtwppgh/c/EU7el1KviwhiZtMrdQd9NDWoI6qqNsT8sXlz1TMUHzDBAo7Q8Kb4yK6xyCY/EnGjgVQm8vauSWj3klPO4vFd4vLzrEMc8LkRrQ+7S+H/e9h9cPhTBuh3NDsHr/RWVwtw6tl4TAZ+Ehf7tXvCgaoA4ay7SfEEOLUG8iDxuYv5zl4LrHG+0hRhTRYHP2t2oyYKi5PnUM0CELQeYnNbxl+Nb+tSP+MtHHNcvVV/JRkeP+45j/FZ1jg8RSVHO0LoSP4Yq32Bww8lyxR+bMKHi2U7TgO/jmhw8Yl9Hza14XKae+3TG8m/kAaovcLWwG3L7qGhLzLBFtxGGD1gNBcbNjanL7bmGQYcZL9s08oPLQ85gM4r1678dCCfGnL0NkIThd/HW5+2cUtFUZ8WJuAPP/r6Nf27YP2hoY8YwbDIZmN1/d2kWxuIA5ZoBKsXBoT3dKxHi7y/obHTYUhXqbWFd4dy5utXfCSNI4FL/dQKnhYXo2dcKmv5LVYupaLvnCCPpUACYQV1De9UHEQfsTbyu+0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
