travis:
  secure:
    BINSTAR_TOKEN: WYryhfAnU4Q8mcxJVGq4MjW+pWb96VNcChyJRxGabfDcDjnUYjUWY0MC8WbDFTucIn4LEc0LiuTSCfjowvlXUutUMxG9jQj6Z+7iue8UhQAm6bfPNeGE8Vin8zZAxJzMERqrToB4yBAUpcu3LPM02Xs1+BgxgZId2xMHR8nQ52KOlbNXze5Vbd1K/huL2g3pD/9ThtrAU/SSWGp2+vyKfjPD3WLlEXwSTofoEI8UuMQ9moh4zpfnn0Enugg/C7UtQ/WOgbjQmgtm0MFEanG5/aQrBXbemDYF/ByHgXgnbfgCla7Gqi/oU44tPBKpWSCQ7l/KsxTe2/dZI43JUbeaAl/KBoEHhWZXCSdNGYcRPOGISqwRCFukW6BkrQX/VbCY3viJgtXBjrEVgbSlyTnGcmmNJH/uup/Iewa5AvwJZmSh0SpPJD+YG3iy4NtiXtNcpBSG0NZUCfiY8Dd4RFjvYkErjPpLMTUQhNi3BvX3PaOlD8vIY9vVIbcEIwcKA8CurXvY4J8ttyUFfIa9EnsxRBTcbZu7Im1kt3JOIfhOUQ44FjazjPZBfSN9rdeUmzwVRHYqPU2PkbVGJgkLejP7OSpvEKIO5qzAGFMiFteSxYc1Z/zzZhj/+DEZ3St6+qt2l4wePqWB2VhsBI9RqXL5MWEQ7urw16Zjl2DcFxCq3Wk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
