travis:
  secure:
    BINSTAR_TOKEN: S8KtbCvBDTD0Yo4qnu3dHtrdjspZuyJ+KDlYfv9gzv0Fc5eKnj3NbOtZAqBXjanDjQfl71rXQsH2rOuvDA5OK0WBGU5opLdCXDmt4ZF79lNiebvS/wKjFgVQVDbg/EiffrTwyCt2Q1TRvOdql6kdCL7H/kwMK7GoAOvj176E1p4LNQz3h15DLr+wYy3kwX0vpQi6r/rAYqeTFAEcnFXpwFLMKj4JgW44ey3pR4MKzwksS54TF3raPW38+J6DjoJLBTiw+iZlBYSSQdY5lvHxvso3TAVKuPulbqGPsHVGALVORM2gm2fsiQuUV5spBR8Jv75Ooll/Im9qJnRG+kGafC0th40OEHSJy2iF/RFfa1f6LXRruD+RRDuVLwMEBOdwrr27MxeaYqNSemNAB45aJD7B6VWR3vISrYMTbXPkye7AtY0er5YQg0f05iM8PwRRGGkIX7MEQW09qPemAzgOwwyWhL5VvTCtoDw8h/6UUmbelZ3BpCVawZR6ZRX44HCqKUhB5jvKQDfmNLVIv7DMCEace/dXhh+XaDnWjwhqwM86XHcBQ3SXFFJpZHUrd1/hT5UGY2gQ0L4TtcnNSHtbKntCPmGAlQLSZHa9MHdXok86cdFFSQgimLRjHZVGh0CmTpKubviKy80I9lkaKyOsrIqyk+TC9iUeW9386jNBEx4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
