travis:
  secure:
    BINSTAR_TOKEN: FtIceYOYAZ37rAY7+pvjuBrlKyZ8T3uEGG1fvNoDr7ldVEmdkkejOBoAKlQG+Iu2w84rD8o2ABSqeyYTzFTYczCTqMwrmf6lSP/v5bjoOWNgUBbAg6N/N2ElmZ0jQ19sqiwlvHB46WkJuF1NcNp/fZivqucQGK6OpC0CQT8NeeHoqiBhYqaHSxzkHailUDMSGH3zk/743acSCYeJ6DgwxcRs6emuLWJU4Jekt7PGDgAH4kn/O1pzKJ4ZHaHf8JYtTVkqd/i/9lHlTMqZvWohfwHuqpwXD3ZuoKxf4mVtlaakoJFPmk/LggDU+n2btWY/otywmJawowckRGzomziAod7nPGT6jDokeSd5twJmqTbmIb9uDjHtjtL2htexZ784uWOXum8d78L/3aPkB3nQw3XPyQ9edDffQ+JhzFPuV+tRor83z8BqNdmmeJWMhVvn0CBQ7volLyaeqbzHvuWsMeiScaKdLKxXnxO3BDxqkOvupYVOjk/n8L6pfSDNsmt56SgiediUQuOY3zgJEGVMRSDaAq3AUYEHvoXPxw+gukJBDRKftM9kW9lxunREHoXDYoAjJlxM3Y/NC8Mjs7eSLPcSNmuyFIHvpphjjyA29dvVGyqjwJCCJzNy02VmYdCfwnnsYzZtRxCQNTd3AWXl/i1c1Zjd7SVaSxghbMd2rD4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
