travis:
  secure:
    BINSTAR_TOKEN: Bd/SdUysx016pcx7c51GOkSJlAMPfEnKKBz1Ut/WAmrxb2wVpfmwqNZbpJYqlscV1kE5Un1X35SQ2UP75Joc4N/uJex2j9ngeRhkB0KPfA/2qYq8cF60kBkzULvzz6UMEqZKOjLZkVccEfedp+anVzgzlR8Ltt2cbLVxyq2thhYMnW2vZ6FAWqu59RPFAAdMZl7Y9tMCiFV7icDYOb1BwZ8rFSYauhhtemcj6Q+6/lj/XRCet5Tf7LdPbjepCinOkzrCxPytgcKFZnyfQBRy6KgLnz8iDEM3VWV/+bwRlTHBWJfpVWi65ShPMP0tgxsNZ4uss91y+6P0nlDbfWQBAEd9/JMU9uj4XHOrLekfvL2vvuHF0GBJYFlqMo+i22zcmThxeSbXPh/XhVc0peqtcPQ9jv7W10IMPZ6MtSveWEiXEdijOpR4NZiwS+xbZ2Zo6NwRkfCJ4R/gZ/9PKL2LORRTbuOIXTy2t22Kk3c0kRaQO9Nuw9t1OEJXZ668MApVeDSYbIgxtdVHTO1JfB1jkYAB/ynei3yVdKEFGU18he4zlKwgDZaCQR/Z793No+UQmZ4YH8tx09G1IMZmUb83DBVyYN1K1Vy96h4epUKqb4rBCavCpBhjLyLO+5VJvVh7a26kDtAgZvuuqJw1XnfEEwo8gD7+NnCLf+GpVh2iQRI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
